cat medicine1.sql>>medicine.sql
cat medicine2.sql>>medicine.sql
cat medicine3.sql>>medicine.sql
cat medicine4.sql>>medicine.sql
cat medicine5.sql>>medicine.sql
cat medicine6.sql>>medicine.sql
cat medicine7.sql>>medicine.sql
cat medicine8.sql>>medicine.sql
cat medicine9.sql>>medicine.sql
cat medicine10.sql>>medicine.sql
cat medicine11.sql>>medicine.sql
cat medicine12.sql>>medicine.sql
cat medicine13.sql>>medicine.sql
cat medicine14.sql>>medicine.sql
cat medicine15.sql>>medicine.sql
cat medicine16.sql>>medicine.sql
cat medicine17.sql>>medicine.sql
cat medicine18.sql>>medicine.sql
cat medicine19.sql>>medicine.sql
cat medicine20.sql>>medicine.sql
cat medicine21.sql>>medicine.sql
cat medicine22.sql>>medicine.sql
cat medicine23.sql>>medicine.sql
cat medicine24.sql>>medicine.sql
cat medicine25.sql>>medicine.sql
cat medicine26.sql>>medicine.sql
cat medicine27.sql>>medicine.sql
cat medicine28.sql>>medicine.sql
cat medicine29.sql>>medicine.sql
cat medicine30.sql>>medicine.sql
