insert into brand (brandId, brandName, factoryId) values (31, 'Allergy', 2);
insert into brand (brandId, brandName, factoryId) values (32, 'Shopko Antibacterial Hand Sanitizer', 2);
insert into brand (brandId, brandName, factoryId) values (33, 'Pramipexole Dihydrochloride', 2);
insert into brand (brandId, brandName, factoryId) values (34, 'THE FLOWER UV INTENSE PACT', 2);
insert into brand (brandId, brandName, factoryId) values (35, 'Lucky Super Soft', 2);
insert into brand (brandId, brandName, factoryId) values (36, 'cephalexin', 2);
insert into brand (brandId, brandName, factoryId) values (37, 'BETULA LENTA POLLEN', 2);
insert into brand (brandId, brandName, factoryId) values (38, 'Zonisamide', 2);
insert into brand (brandId, brandName, factoryId) values (39, 'Oxygen', 2);
insert into brand (brandId, brandName, factoryId) values (40, 'Valstar', 2);
insert into brand (brandId, brandName, factoryId) values (41, 'DR. IASO', 2);
insert into brand (brandId, brandName, factoryId) values (42, 'Isoniazid', 2);
insert into brand (brandId, brandName, factoryId) values (43, 'DOUBLE PERFECTION LUMIERE', 2);
insert into brand (brandId, brandName, factoryId) values (44, 'Cough Relief', 2);
insert into brand (brandId, brandName, factoryId) values (45, 'One Seed Juniper', 2);
insert into brand (brandId, brandName, factoryId) values (46, 'Western Mugwort Sage', 2);
insert into brand (brandId, brandName, factoryId) values (47, 'Doribax', 2);
insert into brand (brandId, brandName, factoryId) values (48, 'Methimazole', 2);
insert into brand (brandId, brandName, factoryId) values (49, 'Oxygen', 2);
insert into brand (brandId, brandName, factoryId) values (50, 'Mirapex', 2);
insert into brand (brandId, brandName, factoryId) values (51, 'Lidocaine Hydrochloride', 2);
insert into brand (brandId, brandName, factoryId) values (52, 'Paroxetine', 2);
insert into brand (brandId, brandName, factoryId) values (53, 'Gabapentin', 2);
insert into brand (brandId, brandName, factoryId) values (54, 'Methylin', 2);
insert into brand (brandId, brandName, factoryId) values (55, 'Pantoprazole Sodium', 2);
insert into brand (brandId, brandName, factoryId) values (56, 'Diclofenac Sodium', 2);
insert into brand (brandId, brandName, factoryId) values (57, 'Good Sense Mucus Relief', 2);
insert into brand (brandId, brandName, factoryId) values (58, 'Paroxetine', 2);
insert into brand (brandId, brandName, factoryId) values (59, 'Omeprazole', 2);
insert into brand (brandId, brandName, factoryId) values (60, 'BioTPres', 2);
