insert into brand (brandId, brandName, factoryId) values (121, 'GABA', 5);
insert into brand (brandId, brandName, factoryId) values (122, 'ADVANCED HYDRO-LIQUID COMPACT (REFILL)', 5);
insert into brand (brandId, brandName, factoryId) values (123, 'Naproxen', 5);
insert into brand (brandId, brandName, factoryId) values (124, 'Antiseptic', 5);
insert into brand (brandId, brandName, factoryId) values (125, 'TRANZGEL', 5);
insert into brand (brandId, brandName, factoryId) values (126, 'Fluconazole', 5);
insert into brand (brandId, brandName, factoryId) values (127, 'Category II', 5);
insert into brand (brandId, brandName, factoryId) values (128, 'Qualaquin', 5);
insert into brand (brandId, brandName, factoryId) values (129, 'CEFPODOXIME PROXETIL', 5);
insert into brand (brandId, brandName, factoryId) values (130, 'AK-Con', 5);
insert into brand (brandId, brandName, factoryId) values (131, 'Metaproterenol Sulfate', 5);
insert into brand (brandId, brandName, factoryId) values (132, 'Nateglinide', 5);
insert into brand (brandId, brandName, factoryId) values (133, 'Ibuprofen', 5);
insert into brand (brandId, brandName, factoryId) values (134, 'Levetiracetam', 5);
insert into brand (brandId, brandName, factoryId) values (135, 'Aspergillus terreus', 5);
insert into brand (brandId, brandName, factoryId) values (136, 'Lactated Ringers', 5);
insert into brand (brandId, brandName, factoryId) values (137, 'Publix', 5);
insert into brand (brandId, brandName, factoryId) values (138, 'GRAPHITES', 5);
insert into brand (brandId, brandName, factoryId) values (139, 'Ondansetron Hydrochloride', 5);
insert into brand (brandId, brandName, factoryId) values (140, 'Geum Gentian 1 Special Order', 5);
insert into brand (brandId, brandName, factoryId) values (141, 'DayTime Cold and Flu', 5);
insert into brand (brandId, brandName, factoryId) values (142, 'Senna- S', 5);
insert into brand (brandId, brandName, factoryId) values (143, 'Sodium Bicarbonate', 5);
insert into brand (brandId, brandName, factoryId) values (144, 'Koh Gen DoTriple Lighting', 5);
insert into brand (brandId, brandName, factoryId) values (145, 'Ultram', 5);
insert into brand (brandId, brandName, factoryId) values (146, 'Nifedipine', 5);
insert into brand (brandId, brandName, factoryId) values (147, 'Colchicine', 5);
insert into brand (brandId, brandName, factoryId) values (148, 'Chlorpromazine Hydrochloride', 5);
insert into brand (brandId, brandName, factoryId) values (149, 'Myferon 150 Forte', 5);
insert into brand (brandId, brandName, factoryId) values (150, 'Daytime Multi-Symptom Cold Relief', 5);
