insert into brand (brandId, brandName, factoryId) values (91, 'Vomiting Diarrhea', 4);
insert into brand (brandId, brandName, factoryId) values (92, 'LAMIVUDINE', 4);
insert into brand (brandId, brandName, factoryId) values (93, 'Aunt Bees Five Flavors', 4);
insert into brand (brandId, brandName, factoryId) values (94, 'LBEL Couleur Luxe Rouge Amplifier XP amplifying SPF 15', 4);
insert into brand (brandId, brandName, factoryId) values (95, 'Loratadine', 4);
insert into brand (brandId, brandName, factoryId) values (96, 'Olanzapine', 4);
insert into brand (brandId, brandName, factoryId) values (97, 'Sani Professional Brand Sani-Hands', 4);
insert into brand (brandId, brandName, factoryId) values (98, 'Lamotrigine', 4);
insert into brand (brandId, brandName, factoryId) values (99, 'Lisinopril with Hydrochlorothiazide', 4);
insert into brand (brandId, brandName, factoryId) values (100, 'Phendimetrazine Tartrate', 4);
insert into brand (brandId, brandName, factoryId) values (101, 'Levofloxacin', 4);
insert into brand (brandId, brandName, factoryId) values (102, 'Nicotine Polacrilex, Coated Mint Flavor', 4);
insert into brand (brandId, brandName, factoryId) values (103, 'Pramipexole Dihydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (104, 'Aspirin', 4);
insert into brand (brandId, brandName, factoryId) values (105, 'TOPIRAMATE', 4);
insert into brand (brandId, brandName, factoryId) values (106, 'Fluvoxamine Maleate', 4);
insert into brand (brandId, brandName, factoryId) values (107, 'Ondansetron', 4);
insert into brand (brandId, brandName, factoryId) values (108, 'Prostatone', 4);
insert into brand (brandId, brandName, factoryId) values (109, 'Antiperspirant', 4);
insert into brand (brandId, brandName, factoryId) values (110, 'pseudoephedrine hydrochloride', 4);
insert into brand (brandId, brandName, factoryId) values (111, 'Ondansetron', 4);
insert into brand (brandId, brandName, factoryId) values (112, 'ACTEMRA', 4);
insert into brand (brandId, brandName, factoryId) values (113, 'omeprazole', 4);
insert into brand (brandId, brandName, factoryId) values (114, 'Azathioprine', 4);
insert into brand (brandId, brandName, factoryId) values (115, 'triamcinolone acetonide', 4);
insert into brand (brandId, brandName, factoryId) values (116, 'Thiothixene', 4);
insert into brand (brandId, brandName, factoryId) values (117, 'Thyrostat', 4);
insert into brand (brandId, brandName, factoryId) values (118, 'SKIN 79 The Prestige Beblesh Balm (5g)', 4);
insert into brand (brandId, brandName, factoryId) values (119, 'Treatment Set TS333176', 4);
insert into brand (brandId, brandName, factoryId) values (120, 'levomefolate calcium and schizochytrium dha', 4);
