insert into brand (brandId, brandName, factoryId) values (151, 'LBEL COULEUR LUXE AMPLIFIER XP', 6);
insert into brand (brandId, brandName, factoryId) values (152, 'Clotrimazole', 6);
insert into brand (brandId, brandName, factoryId) values (153, 'amoxicillin and clavulanate potassium', 6);
insert into brand (brandId, brandName, factoryId) values (154, 'Daytime Cold and Flu Relief', 6);
insert into brand (brandId, brandName, factoryId) values (155, 'Tindamax', 6);
insert into brand (brandId, brandName, factoryId) values (156, 'Nabumetone', 6);
insert into brand (brandId, brandName, factoryId) values (157, 'Propranolol Hydrochloride', 6);
insert into brand (brandId, brandName, factoryId) values (158, 'Digoxin', 6);
insert into brand (brandId, brandName, factoryId) values (159, 'Lovenox', 6);
insert into brand (brandId, brandName, factoryId) values (160, 'Quality Choice Nighttime Severe Cold and Cough', 6);
insert into brand (brandId, brandName, factoryId) values (161, 'JIANZE FIRST AID ANTISEPTIC SKIN TOWELETTE', 6);
insert into brand (brandId, brandName, factoryId) values (162, 'Methocarbamol', 6);
insert into brand (brandId, brandName, factoryId) values (163, 'Good Neighbor Pharmacy headache relief', 6);
insert into brand (brandId, brandName, factoryId) values (164, 'Ranitidine', 6);
insert into brand (brandId, brandName, factoryId) values (165, 'Pancreas Meteoric Iron Special Order', 6);
insert into brand (brandId, brandName, factoryId) values (166, 'Sucralfate', 6);
insert into brand (brandId, brandName, factoryId) values (167, 'LBEL EFFET PARFAIT MINERAL NATURAL SKIN EFFECT MOUSSE FOUNDATION SPF 16', 6);
insert into brand (brandId, brandName, factoryId) values (168, 'Lactulose', 6);
insert into brand (brandId, brandName, factoryId) values (169, 'YAM DOUBLE CARE FLUID', 6);
insert into brand (brandId, brandName, factoryId) values (170, 'Hydromorphone HCl', 6);
insert into brand (brandId, brandName, factoryId) values (171, 'Articula', 6);
insert into brand (brandId, brandName, factoryId) values (172, 'Stool Softener', 6);
insert into brand (brandId, brandName, factoryId) values (173, 'Erythromycin', 6);
insert into brand (brandId, brandName, factoryId) values (174, 'Clarins Broad Spectrum SPF 30 Sunscreen for Sun-Sensitive Areas', 6);
insert into brand (brandId, brandName, factoryId) values (175, 'Atenolol', 6);
insert into brand (brandId, brandName, factoryId) values (176, 'ARTISS', 6);
insert into brand (brandId, brandName, factoryId) values (177, 'DONEPEZIL HYDROCHLORIDE', 6);
insert into brand (brandId, brandName, factoryId) values (178, 'SACCHAROMYCES CEREVISIAE', 6);
insert into brand (brandId, brandName, factoryId) values (179, 'Carisoprodol', 6);
insert into brand (brandId, brandName, factoryId) values (180, 'YS Solution Intensive AC Care', 6);
