insert into brand (brandId, brandName, factoryId) values (61, 'Camphor, Menthol', 3);
insert into brand (brandId, brandName, factoryId) values (62, 'sunmark ibuprofen', 3);
insert into brand (brandId, brandName, factoryId) values (63, 'Amoxicillin', 3);
insert into brand (brandId, brandName, factoryId) values (64, 'Luminous Live Aura CC', 3);
insert into brand (brandId, brandName, factoryId) values (65, 'GENOTROPIN', 3);
insert into brand (brandId, brandName, factoryId) values (66, 'SPF-60', 3);
insert into brand (brandId, brandName, factoryId) values (67, 'Acyclovir', 3);
insert into brand (brandId, brandName, factoryId) values (68, 'citalopram hydrobromide', 3);
insert into brand (brandId, brandName, factoryId) values (69, 'Topamax', 3);
insert into brand (brandId, brandName, factoryId) values (70, 'Cold and Sinus Maximum Strength', 3);
insert into brand (brandId, brandName, factoryId) values (71, 'Premier Value Chest Congestion Relief', 3);
insert into brand (brandId, brandName, factoryId) values (72, 'Ampicillin', 3);
insert into brand (brandId, brandName, factoryId) values (73, 'Pollens - Weeds and Garden Plants, Nettle Urtica dioica', 3);
insert into brand (brandId, brandName, factoryId) values (74, 'Glipizide', 3);
insert into brand (brandId, brandName, factoryId) values (75, 'Gemfibrozil', 3);
insert into brand (brandId, brandName, factoryId) values (76, 'Ultra-TechneKow', 3);
insert into brand (brandId, brandName, factoryId) values (77, 'Imari Seduction', 3);
insert into brand (brandId, brandName, factoryId) values (78, 'Depression Complex', 3);
insert into brand (brandId, brandName, factoryId) values (79, 'Defensol D', 3);
insert into brand (brandId, brandName, factoryId) values (80, 'UltrasolSunscreen', 3);
insert into brand (brandId, brandName, factoryId) values (81, 'Ephedrine Sulfate', 3);
insert into brand (brandId, brandName, factoryId) values (82, 'TRAMADOL HYDROCHLORIDE', 3);
insert into brand (brandId, brandName, factoryId) values (83, 'Persantine', 3);
insert into brand (brandId, brandName, factoryId) values (84, 'Lidocaine Hydrochloride and Epinephrine', 3);
insert into brand (brandId, brandName, factoryId) values (85, 'Salicylic Acid 6 percent', 3);
insert into brand (brandId, brandName, factoryId) values (86, 'LBEL MAXIMUM COMFORT AND LONG-LASTING FOUNDATION SPF 10', 3);
insert into brand (brandId, brandName, factoryId) values (87, 'Ulta Red Raspberry Anti-Bacterial Deep Cleansing', 3);
insert into brand (brandId, brandName, factoryId) values (88, 'ANTI BACTERIAL HAND SANITIZER', 3);
insert into brand (brandId, brandName, factoryId) values (89, 'Colocynthis Kit Refill', 3);
insert into brand (brandId, brandName, factoryId) values (90, 'COLLAGEN HD FOUNDATION', 3);
