insert into brand (brandId, brandName, factoryId) values (1, 'CATTLE HAIR AND EPITHELIA', 1);
insert into brand (brandId, brandName, factoryId) values (2, 'Nu Skin Nu Colour', 1);
insert into brand (brandId, brandName, factoryId) values (3, 'AN ADC WRINKLE', 1);
insert into brand (brandId, brandName, factoryId) values (4, 'Viagra', 1);
insert into brand (brandId, brandName, factoryId) values (5, 'Opahl', 1);
insert into brand (brandId, brandName, factoryId) values (6, 'DERMOPLUS MEDICATED', 1);
insert into brand (brandId, brandName, factoryId) values (7, 'Presidents Choice', 1);
insert into brand (brandId, brandName, factoryId) values (8, 'LivRelief', 1);
insert into brand (brandId, brandName, factoryId) values (9, 'ondansetron hydrochloride', 1);
insert into brand (brandId, brandName, factoryId) values (10, 'GENGRAF', 1);
insert into brand (brandId, brandName, factoryId) values (11, 'Bahia Grass', 1);
insert into brand (brandId, brandName, factoryId) values (12, 'Nettle', 1);
insert into brand (brandId, brandName, factoryId) values (13, 'kids cough cold and throat', 1);
insert into brand (brandId, brandName, factoryId) values (14, 'Petroleum Skin Protectant', 1);
insert into brand (brandId, brandName, factoryId) values (15, 'Lari-Clear', 1);
insert into brand (brandId, brandName, factoryId) values (16, 'Simvastatin', 1);
insert into brand (brandId, brandName, factoryId) values (17, 'Meprobamate', 1);
insert into brand (brandId, brandName, factoryId) values (18, 'DONEPEZIL HYDROCHLORIDE', 1);
insert into brand (brandId, brandName, factoryId) values (19, 'YOUTH FULL TINTED MOISTURIZER', 1);
insert into brand (brandId, brandName, factoryId) values (20, 'Dexamethasone', 1);
insert into brand (brandId, brandName, factoryId) values (21, 'Mesna', 1);
insert into brand (brandId, brandName, factoryId) values (22, 'Golden Sunshine Far Infrared COOL Herbal', 1);
insert into brand (brandId, brandName, factoryId) values (23, 'Loperamide Hydrochloride', 1);
insert into brand (brandId, brandName, factoryId) values (24, 'Glipizide', 1);
insert into brand (brandId, brandName, factoryId) values (25, 'Cardizem', 1);
insert into brand (brandId, brandName, factoryId) values (26, 'Anti-Bacterial Gentle Foaming Hand', 1);
insert into brand (brandId, brandName, factoryId) values (27, 'ShopRite Ni Calm', 1);
insert into brand (brandId, brandName, factoryId) values (28, 'La Roche Posay Laboratoire Dermatologique Anthelios 60 Melt In Sunscreen Milk Broad Spectrum SPF 60 Face and Body', 1);
insert into brand (brandId, brandName, factoryId) values (29, 'Aveeno Baby Eczema Therapy Soothing Bath Treatment', 1);
insert into brand (brandId, brandName, factoryId) values (30, 'Hydrochlorothiazide', 1);
